version: '3.8'

services:
  maps-leads-collector:
    container_name: maps-leads-collector
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app/src  # Sync local source code
      - ../.env:/app/.env  # Sync environment variables
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    networks:
      - scraper-net

networks:
  scraper-net:
    driver: bridge
